title: My Data Science Portfolio
description: A collection of my data science projects.
baseurl: "/Data-Science-Projects"  # Adjust if your site is hosted in a subpath
url: "https://dam-runner.github.io/Data-Science-Projects/"
theme: jekyll-theme-minimal
github_username: dam-runner
show_downloads: true
